"""
This type stub file was generated by pyright.
"""

import gym
import numpy as np
from typing import Any, Union
from ding.envs.env import BaseEnv

class DemoEnv(BaseEnv):
    def __init__(self, cfg: dict) -> None:
        ...
    
    @property
    def observation_space(self) -> gym.spaces.Space:
        ...
    
    @property
    def action_space(self) -> gym.spaces.Space:
        ...
    
    @property
    def reward_space(self) -> gym.spaces.Space:
        ...
    
    def reset(self) -> Any:
        """
        Overview:
            Resets the env to an initial state and returns an initial observation. Abstract Method from ``gym.Env``.
        """
        ...
    
    def close(self) -> None:
        ...
    
    def step(self, action: Any) -> BaseEnv.timestep:
        ...
    
    def seed(self, seed: int) -> None:
        ...
    
    def random_action(self) -> Union[np.ndarray, int]:
        ...
    
    def __repr__(self) -> str:
        ...
    


